module.exports = [
    {
        thumbnail_url: '/images/1.jpg',
        image_url: 'http://localhost:4000/images/1.jpg',
        RR: 0.1,
        CPI: .5,
        CPM: 1,
        CTR: 1,
        CVR: 1,
        CPC: 1,
        install: 1000,
        update_time: 2018,
        evaluation: 'good',
        key: 1,
        material_id: 1
    },
    {
        thumbnail_url: '/images/1.jpg',
        image_url: 'http://localhost:4000/images/1.jpg',
        RR: 0.1,
        CPI: .5,
        CPM: 1,
        CTR: 1,
        CVR: 1,
        CPC: 1,
        install: 1000,
        update_time: 2018,
        evaluation: 'normal',
        key: 2,
        material_id: 1
    },
    {
        thumbnail_url: '/images/1.jpg',
        image_url: 'http://localhost:4000/images/1.jpg',
        RR: 0.1,
        CPI: .5,
        CPM: 1,
        CTR: 1,
        CVR: 1,
        CPC: 1,
        install: 1000,
        update_time: 2018,
        evaluation: 'poor',
        key: 3,
        material_id: 1
    },
];
